#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 JSON_FILEPATH" >&2
  exit 1
fi
if ! [ -e "$1" ]; then
  echo "$1 not found" >&2
  exit 1
fi
if ! [ -f "$1" ]; then
  echo "$1 not a file" >&2
  exit 1
fi

if ! command -v jq &> /dev/null
then
    echo "jq could not be found"
    echo "i really really wanted to work with json so i need jq, pls install jq"
    echo "to install:"
    echo "    sudo apt update"
    echo "    sudo apt install jq" 
    exit 1
fi

if ! jq -e . >/dev/null 2>&1 <<<$(cat $1); then
    echo "not a valid JSON file"
    exit 1
fi

FILE_PATH=$1
VAGRANT_EXAMPLE=~/Desktop/nebulaProject/Vagrant/vagrant_esempio3_nebula
NUMBER_OF_HOST=$(jq 'length' $FILE_PATH)
for i in $(seq 0 $((NUMBER_OF_HOST - 1)))
do
	HOST_NAME=$(jq ".[$i].name" $FILE_PATH | tr -d \" )
	DIR=$PWD
	cd $VAGRANT_EXAMPLE
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/scripts/setup-host $HOST_NAME:.
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/scripts/nebula $HOST_NAME:.
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/scripts/ca.crt $HOST_NAME:.
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/$HOST_NAME.crt $HOST_NAME:.
	rm ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/$HOST_NAME.crt
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/$HOST_NAME.key $HOST_NAME:.
	rm ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/$HOST_NAME.key
	vagrant scp ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/config_$HOST_NAME.yaml $HOST_NAME:.
	rm ~/Desktop/nebulaProject/NebulaAppV3/TmpFileGenerated/config_$HOST_NAME.yaml
	cd $DIR
done




